<a href="https://colab.research.google.com/github/nou619/Discord-meme-bot/blob/main/leaningpytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
print('yo')

yo


In [14]:
 import torch
 import pandas as pd
 import numpy as np
 import matplotlib.pyplot as plt


In [15]:
print(torch.__version__)

2.8.0+cu126


In [16]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [17]:
scalar.ndim

0

In [18]:
scalar.item()

7

In [19]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [20]:
vector.shape

torch.Size([2])

In [21]:
MATRIX=torch.tensor([ [7,8], [9,10] ])

In [22]:
MATRIX.shape

torch.Size([2, 2])

In [23]:
MATRIX.ndim

2

In [24]:
TENSOR=torch.tensor([[[1,2,3], [4,5,6] ,[7,8,9]]])

In [25]:
TENSOR.ndim

3

In [26]:
TENSOR.shape

torch.Size([1, 3, 3])

In [27]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.8319, 0.6459, 0.8810, 0.4703],
        [0.8252, 0.7419, 0.9315, 0.3315],
        [0.6303, 0.8515, 0.9452, 0.7808]])

In [28]:
random_tensor.ndim

2

In [29]:
random_image_size_tensor=torch.rand(size=(3,224,224))

In [30]:
random_image_size_tensor.shape

torch.Size([3, 224, 224])

In [31]:
zeros=torch.zeros(3,4)

In [32]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
ones=torch.ones(3,1)

In [34]:
ones

tensor([[1.],
        [1.],
        [1.]])

In [35]:
TENSOR.dtype

torch.int64

In [36]:
zeros.dtype

torch.float32

In [37]:
torch.range(1,5)

/tmp/ipython-input-2886557097.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,5)


tensor([1., 2., 3., 4., 5.])

In [38]:
zero_to_four=torch.arange(5)
zero_to_four

tensor([0, 1, 2, 3, 4])

In [39]:
five_zeros=torch.zeros_like(input=zero_to_four)
five_zeros

tensor([0, 0, 0, 0, 0])

In [40]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None,device=None, requires_grad=False)

In [41]:
float_32_tensor.dtype

torch.float32

In [42]:
float_16_tensor=float_32_tensor.type(torch.float16)

In [43]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [44]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [45]:
#getting information from tensors
#1.tensors not right datatype-
#2.tensors not right shape
#3.tensors not on the right device

In [46]:
some_tensor=torch.rand(3,4)

In [47]:
print(f"datatype of tensor  {some_tensor.dtype}")

datatype of tensor  torch.float32


In [48]:
print(f"device of tensor  {some_tensor.device}")

device of tensor  cpu


tensor operations


In [49]:
tensor=torch.tensor([1,2,3])

In [50]:
tensor+10


tensor([11, 12, 13])

In [51]:
tensor*10

tensor([10, 20, 30])

In [52]:
tensor-10

tensor([-9, -8, -7])

In [53]:
tensor//10

tensor([0, 0, 0])

In [54]:
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [55]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [56]:
tensor

tensor([1, 2, 3])

In [57]:
#torch.add

In [58]:
###matrix multiplication

In [59]:
torch.matmul(tensor,tensor)

tensor(14)

In [60]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
value


CPU times: user 564 µs, sys: 799 µs, total: 1.36 ms
Wall time: 1.32 ms


tensor(14)

In [61]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 147 µs, sys: 872 µs, total: 1.02 ms
Wall time: 988 µs


tensor(14)

In [62]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.4471, 0.4673, 0.6535],
        [0.5543, 0.5913, 0.8153],
        [0.5037, 0.4072, 0.6845]])

In [63]:
torch.rand(3,2) @ torch.rand(2,3)

tensor([[0.4014, 0.4303, 0.5558],
        [0.6605, 0.8911, 1.0274],
        [0.5341, 0.3553, 0.6055]])

In [64]:
tensor_a=torch.rand(3,4)
tensor_b=torch.rand(3,2)

In [65]:
tensor_b

tensor([[0.3302, 0.3632],
        [0.6245, 0.3875],
        [0.0454, 0.3528]])

In [66]:
tensor_b.T

tensor([[0.3302, 0.6245, 0.0454],
        [0.3632, 0.3875, 0.3528]])

In [67]:
x=torch.arange(0,100,10)

In [68]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [69]:
tensor.argmax()

tensor(2)

In [70]:
tensor[2]

tensor(3)

In [ ]:
#reshaping , stacing ,squeezing and unsquizing

In [71]:
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [74]:
x_reshaped=x.reshape(1,9)

In [75]:
x_reshaped2=x.reshape(9,1)

In [76]:
y=torch.arange(1,11)

In [77]:
y_reshaped=y.reshape(5,2)